version: "3.8"

services:
  web:
    build: .
    container_name: devops_web
    ports:
      - "5000:5000"
    restart: always
    networks:
      - monitoring_net

  prometheus:
    image: prom/prometheus:latest
    container_name: devops_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
    ports:
      - "9090:9090"
    networks:
      - monitoring_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: devops_alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - monitoring_net

  grafana:
    image: grafana/grafana:latest
    container_name: devops_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge

volumes:
  grafana_data:
